apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "new-api.fullname" . }}-config
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.config.timezone | quote }}
  {{- if and .Values.ingress.enabled (gt (len .Values.ingress.hosts) 0) }}
  {{- $host := index .Values.ingress.hosts 0 }}
  FRONTEND_BASE_URL: {{ printf "https://%s" $host.host | quote }}
  {{- else }}
  FRONTEND_BASE_URL: {{ .Values.config.frontendBaseUrl | quote }}
  {{- end }}
  SYNC_FREQUENCY: {{ .Values.config.syncFrequency | quote }}
  BATCH_UPDATE_ENABLED: {{ .Values.config.batchUpdate.enabled | quote }}
  BATCH_UPDATE_INTERVAL: {{ .Values.config.batchUpdate.interval | quote }}
  MEMORY_CACHE_ENABLED: {{ .Values.config.memoryCache.enabled | quote }}
  SESSION_MAX_AGE: {{ .Values.config.session.maxAge | quote }}
  LOG_LEVEL: {{ .Values.config.log.level | quote }}
  SQL_LOG: {{ .Values.config.log.sqlLog | quote }}
  RATE_LIMIT_ENABLED: {{ .Values.config.rateLimit.enabled | quote }}
  RATE_LIMIT_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.requestsPerMinute | quote }}
  {{- range .Values.config.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}