{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.newapi.master.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "new-api.fullname" . }}-master
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "new-api.masterSelectorLabels" . | nindent 6 }}
---
{{- end }}
{{- if .Values.newapi.slave.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "new-api.fullname" . }}-slave
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: slave
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "new-api.slaveSelectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}