apiVersion: v1
kind: Secret
metadata:
  name: {{ include "new-api.fullname" . }}-secrets
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ include "new-api.sessionSecret" . | b64enc | quote }}
  crypto-secret: {{ include "new-api.cryptoSecret" . | b64enc | quote }}
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ include "new-api.mysql.rootPassword" . | b64enc | quote }}
  mysql-password: {{ include "new-api.mysql.password" . | b64enc | quote }}
  {{- else if .Values.mysql.external.password }}
  mysql-password: {{ .Values.mysql.external.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
  redis-password: {{ include "new-api.redis.password" . | b64enc | quote }}
  {{- else if .Values.redis.external.password }}
  redis-password: {{ .Values.redis.external.password | b64enc | quote }}
  {{- end }}